kind: pipeline
name: default

workspace:
  path: /home/node/app

steps:
  - name: build-image
    image: docker:dind
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: yarncache
        path: /usr/local/share/.cache/yarn
    environment:
      CI: false
      GENERATE_SOURCEMAP: false
      COS_SECRET_ID:
        from_secret: COS_SECRET_ID
      COS_SECRET_KEY:
        from_secret: COS_SECRET_KEY
    commands:
      - docker compose up --build

  - name: deploy
    image: ubuntu:22.04
    volumes:
      - name: webroot
        path: /webroot
    commands:
      - mkdir -p /webroot/paperplane-app/
      - rm -rf /webroot/paperplane-app/*
      - cp -rf ./dist/* /webroot/paperplane-app/

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
  - name: webroot
    host:
      path: /root/www
  - name: yarncache
    host:
      path: /root/.yarncache

trigger:
  branch:
    - master
